[package]
name = "path_facts"
version = "0.1.0"
edition = "2021"

[dependencies]
# We use `faccess` to check **effective** permisisons on disk (includes inherited values)
faccess = "0.2.4"

[dev-dependencies]
indoc = "2.0.5"
tempfile = "3.12.0"
pretty_assertions = "1.4.1"
